# Generated by Django 4.2.9 on 2024-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_resume_user_alter_education_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="languages",
            field=models.ManyToManyField(blank=True, to="resume.language"),
        ),
    ]
